apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency
  namespace: nais-system
  labels:
    app: currency
  annotations:
    iam.gke.io/gcp-service-account: currency-user@nais-io.iam.gserviceaccount.com
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: currency
  namespace: nais-system
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "false"
          labels:
            app: currency
          name: currency
        spec:
          containers:
          - image: IMAGE_TAG
            imagePullPolicy: Always
            name: currency
            envFrom:
              - secretRef:
                  name: currency
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
                ephemeral-storage: 1Gi
              limits:
                cpu: 250m
                memory: 512Mi
                ephemeral-storage: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 65532
              seccompProfile:
                type: RuntimeDefault
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          serviceAccount: currency
          serviceAccountName: currency
          terminationGracePeriodSeconds: 30
  schedule: 0 5 * * *
  successfulJobsHistoryLimit: 1
  suspend: false
