name: Build, push and deploy currency
on:
  push:
    branches:
      - main

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images

jobs:
  build_and_push:
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.6.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-aiven-cost@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/currency
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
      - name: Build and push currency
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile_currency
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy_currency:
    if: github.ref == 'refs/heads/main'
    runs-on: ["fasit-deploy"]
    needs: ["build_and_push"]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout aiven-cost
        uses: actions/checkout@v3.3.0
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-aiven-cost@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Get credentials
        shell: bash
        run: |
          gcloud container clusters get-credentials nais-io --project nais-io --region europe-north1
      - name: deploy currency
        env:
          CURRENCY_TOKEN: ${{ secrets.CURRENCY_TOKEN }}
        shell: bash
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          kubectl create secret generic currency --from-literal=CURRENCY_TOKEN=$CURRENCY_TOKEN --dry-run=client -o yaml | kubectl apply -f -
          sed "s|IMAGE_TAG|${IMAGE_TAG}|g" ./.nais/currency.yaml | kubectl apply -f -
